### ISSUE TITLE
App reestructure

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#119]
Hey everyone! 😃 

I'm so excited to start again/keep working on this awesome project! Since I started contributing, I've noticed that we are not being able to make progress in our features mostly because the main maintainers don't have time to dedicate to it. Also, I find our tech stack very complex. So, I decided to create this issue in order to discuss how we can improve that, to bring up some interesting stuff that I researched, and also as a knowledge transfer. I wanna come up with a new stack (should be an easier one) and improve our work model in general in order to attract more developers to help us. 
I really love to work on Animavita, I could learn a lot contributing here and I don't want this project to die. However, I can't do anything by myself. I hope not to be alone.

## Our goal
Besides helping people who are interested in adopting a pet or putting a pet for adoption, we want to help you to grow as a developer. You can confirm this by reading the section [Contributing](https://github.com/animavita/animavita#handshake-contributing) in our README. As I said above, I learned a lot here. Open source in general is a great way to highlight yourself to the community as well as to show to recruiters during an interview. 
Our last dream for this project is to see it available for download on mobile stores. That would be awesome!

## Difficult to start
If our goal is to help you as a developer, we should be more developer-friendly right? I'm saying that cause I know how hard it is to make your first contribution here, and that's why I made https://github.com/animavita/animavita/pull/84 trying to make this process a little bit easier. But it's still hard because it's not clear or maybe not very well documented how our business rules work. It's hard to understand when you first look at the code.

## First things first
Our current default branch called `next` is actually our 2.0 version which was supposed to be in development. However, we're stuck on this, and that's why I want to restructure the project. Our `master` branch is actually our v1, kudos to @wendelfreitas and @renanmav who made awesome job there! The v1 (master) was finalized by Wendel and we started a v2 because we wanted to improve and launch a new application totally refactored using the latest front-end libraries, adding typescript and so on.

## App Structure
Our application is structured in a monorepo with lerna and yarn workspaces. Each package in this monorepo is responsible for one thing and its name should be very self-explanatory. _e.g. eslint is where we store linter configs._ Our backend is the `graphql` package. Our front-end is the `expo` package. We have our design system completely separated in the `ui` package. All the other packages are consumed by `graphql` and `expo`.
Even though we don't have a firmed pattern to organize our structure, we've been trying to use BDD (I know it's not about folder structure) and separate everything that makes sense to be separated from the other stuff.

## What I wanna change?
Since I'm aware of the downsides of our project, I'm gonna give a few suggestions about what I think would be interesting to change or continue using. All my suggestions are to make this project easier, to get more developers interested in helping us, and to put Animavita on track again. If you already have contributed to Animavita, please, let us know what was most difficult for you. If you had never contributed but got experience working with expo, GraphQL, monorepos, please, leave your opinion as well.

- **Replace relay with apollo.**
Relay is an awesome library created by Facebook. But it's quite complex and less popular than apollo, in my opinion. 
- **Should we use some backend JS framework, like nest, or keep doing everything by hand?**
I've been working more on the front-end side. So I'm not the best person to talk about that.
- **Expo instead of bare react-native**
Expo has improved a lot and I think it solves 90% of our problems. Unless we have a good reason to eject this app, I'd keep expo.
- **State management**
I'll go straight to the point: should we use redux or server-side state management? I'm a big fan of [react-query](https://tanstack.com/query/v4/) 👀 
- **Login by e-mail**
One of the biggest pain for our contributors was having to create a Facebook developer account and set up this in the app in order to have the app running. Let's add login by e-mail to streamline this auth flow.
- **Start from scratch**
Would you rather kill `next` branch and start a new one, or try to refactor what we already have?

Below our v1 running. So before commenting, be aware that we want to keep all features that we previously had on v1.
<p align="center">
  <kbd>
    <img width="250" style="border-radius: 5px" height="450" src="https://i.imgur.com/7CJSiNA.gif" alt="Intro">
  </kbd>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <kbd>
    <img width="250" style="border-radius: 5px" height="450" src="https://i.imgur.com/jxUIe8w.gif" alt="Register adopt">
  </kbd>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <kbd>
    <img width="250" style="border-radius: 5px" height="450" src="https://i.imgur.com/CNczcSk.gif" alt="Chat">
  </kbd>
</p>
 <a href="https://discord.gg/BHHz77rhb6">
    <img src="https://img.shields.io/discord/829042103295410197?color=%237289DA&label=Animavita&logo=discord&logoColor=white" alt="Discord">
  </a>

That's it for now! Let's discuss guys, I need help. Feel free to comment here or to reach out, we also have a discord where you can join.

**Comment by wendelfreitas** [comment]
I was thinking in something more easier to be the first deployed version, something like just (React Native + Firebase). To be able to add this on production asap and collect feedback in the fastest way. After that, we can work with a more structured app using other technologies and create a good part from scratch.

**Comment by wendelfreitas** [comment]
It's a good way to launch the pq facil app but we are adding a lot of complexity, something with simple technologies we can test more things and improve in the future.


We can use:

* Turborepo
* Expo
* Firebase

**Comment by wendelfreitas** [comment]
It's a good way to launch, because it's an easy app but we're adding a lot of complexity, we can do something with simple technologies we can test more things and improve in the future

We can use:

* Expo
* Firebase
* React Query Firebase
* Turborepo

**Comment by wendelfreitas** [comment]
wdyt? @belgamo

**Comment by belgamo** [comment]
Right, sounds good to me but then we should consider some important things, like:

1- **Will our contributors be able to help us since we will use firebase?**
We will add one more external tool, just need to make sure that it's easy to set up. We should try to avoid complexity to get this project set up as we have with Facebook login today...

2- **Is it possible to migrate data from firebase?** 
After deploying, are we able to migrate the data from there? In the future, we might want to use our own DB solution, which might be not easy if we can't get our user data from firebase.

3- **If we decide to go with this approach, we should make sure that we're coding following good practices.**
Like isolating our business rules from firebase implementation and also avoiding high-coupling. So we should structure this in a way that we can easily remove/replace firebase later. For example, let's say we use `@react-query-firebase/auth` to authenticate our users, we should create a wrapper around like a custom hook to be able to easily replace that in the future.

4- **Testing**
Since we want to speed up our v1 to be in prod, I'd add tests at least for the core parts of our app, mostly our business rules to avoid them breaking. Let's take the adoption feature as an example, we can create a custom hook for that, like `useAdoption`. Then we inject all dependencies like our persistency strategy, the involved users, and so on.

**Comment by petruspierre** [comment]
I can understand @wendelfreitas's suggestion, but I don't think there's enough reason to go with that for a project restructuring. How would be that better than v1?

IMHO, adding some complexity would give us scalability and *sustainability* to the project.  

1. Scalability
Firebase is good, I enjoy using it for simple projects. I don't know if we can say Animavita is a simple app, I would say it's a simple idea, but we need to be careful by thinking of it being used by people around the country, that we're building something really useful that will help us evolve as developers but also help people.
If it wouldn't be a refactor, I would say Firebase is a good option because we would understand better the domain and many of the architectural aspects of the project, but that part is done by v1.
Therefore, creating our API will take longer, but I think it pays off because 1. we would learn more and have more people from different specialties working together on this, and 2. we would be more scalable in terms of what we can build and who can we attend.

2. Sustainability
As @belgamo well said, Animavita is where it is now because it's a hard code to understand and to have the onboarding on, some packages and configurations that do not work anymore, and features that only the ones who have developed know how to maintain. It is possible to work on, of course, but no one would like to spend hours and hours trying to first set the project up to then try to understand and finally try something to contribute on.
If we make something simpler by using Firebase and then think about adding more and more features, we would reach the same point the project currently is at. At some point, we would need to migrate to an API where we could use different databases, WebSockets, REST, GraphQL, and I18n. And when that comes in, no one will want to make that migration or will even know how to do that, because it's done with really different tech and possibly done by other people.

Therefore, I think it's not good to start building something we can't see this scalability and sustainability, but I'm eyes open to see other opinions about that.

---

About the app restructuring, I'll give my opinions on what Belgamo suggested:
1. I agree with moving from Relay to Apollo based on what Belgamo described;
2. NestJS is exceptional and I've used in my projects and enjoy it, would give us a lot of productivity and ways to implement a good structure and standards to our modules. As @wendelfreitas said, we've been adding a lot of complexity to the project, but I think most of that complexity is not coming from the code but from what we're using for that (relay, per example) and I think NestJS could help us on that since it has support for a lot of things we use in the project just out of the box.
3. For Animavita, I think Expo is the best way to go, I just think it's a good discussion between proceeding with a Managed Workflow or Bare Workflow because of the same reason I've said about Firebase. Bare Workflow would give us stability in knowing we won't have problems ejecting this project in the future because we know it's a real possibility. Manager workflow would lead us to a first version quicker but I don't see the need for the rush on that.
4. I don't think React Query is a replacement for Redux, really think they can work together, I'm also a big fan of React Query and would use that in the new version for sure.
5. I think a mistake we've committed with this version of Animavita API is the authentication, it's a bit messy and shouldn't be that complex, mainly considering we're just using a Facebook Authentication. NestJS for example has good support for PassportJS out of the box that would help us to have multiple authentication strategies (see)[https://docs.nestjs.com/security/authentication].
6. I would start from scratch.

---

Hope my opinion may be useful for the discussion, I'm open to hearing different perspectives and contributing to this restructuring

**Comment by belgamo** [comment]
> I can understand @wendelfreitas's suggestion, but I don't think there's enough reason to go with that for a project restructuring. How would be that better than v1?
> 
> 
> 
> IMHO, adding some complexity would give us scalability and *sustainability* to the project.  
> 
> 
> 
> 1. Scalability
> 
> Firebase is good, I enjoy using it for simple projects. I don't know if we can say Animavita is a simple app, I would say it's a simple idea, but we need to be careful by thinking of it being used by people around the country, that we're building something really useful that will help us evolve as developers but also help people.
> 
> If it wouldn't be a refactor, I would say Firebase is a good option because we would understand better the domain and many of the architectural aspects of the project, but that part is done by v1.
> 
> Therefore, creating our API will take longer, but I think it pays off because 1. we would learn more and have more people from different specialties working together on this, and 2. we would be more scalable in terms of what we can build and who can we attend.
> 
> 
> 
> 2. Sustainability
> 
> As @belgamo well said, Animavita is where it is now because it's a hard code to understand and to have the onboarding on, some packages and configurations that do not work anymore, and features that only the ones who have developed know how to maintain. It is possible to work on, of course, but no one would like to spend hours and hours trying to first set the project up to then try to understand and finally try something to contribute on.
> 
> If we make something simpler by using Firebase and then think about adding more and more features, we would reach the same point the project currently is at. At some point, we would need to migrate to an API where we could use different databases, WebSockets, REST, GraphQL, and I18n. And when that comes in, no one will want to make that migration or will even know how to do that, because it's done with really different tech and possibly done by other people.
> 
> 
> 
> Therefore, I think it's not good to start building something we can't see this scalability and sustainability, but I'm eyes open to see other opinions about that.
> 
> 
> 
> ---
> 
> 
> 
> About the app restructuring, I'll give my opinions on what Belgamo suggested:
> 
> 1. I agree with moving from Relay to Apollo based on what Belgamo described;
> 
> 2. NestJS is exceptional and I've used in my projects and enjoy it, would give us a lot of productivity and ways to implement a good structure and standards to our modules. As @wendelfreitas said, we've been adding a lot of complexity to the project, but I think most of that complexity is not coming from the code but from what we're using for that (relay, per example) and I think NestJS could help us on that since it has support for a lot of things we use in the project just out of the box.
> 
> 3. For Animavita, I think Expo is the best way to go, I just think it's a good discussion between proceeding with a Managed Workflow or Bare Workflow because of the same reason I've said about Firebase. Bare Workflow would give us stability in knowing we won't have problems ejecting this project in the future because we know it's a real possibility. Manager workflow would lead us to a first version quicker but I don't see the need for the rush on that.
> 
> 4. I don't think React Query is a replacement for Redux, really think they can work together, I'm also a big fan of React Query and would use that in the new version for sure.
> 
> 5. I think a mistake we've committed with this version of Animavita API is the authentication, it's a bit messy and shouldn't be that complex, mainly considering we're just using a Facebook Authentication. NestJS for example has good support for PassportJS out of the box that would help us to have multiple authentication strategies (see)[https://docs.nestjs.com/security/authentication].
> 
> 6. I would start from scratch.
> 
> 
> 
> ---
> 
> 
> 
> Hope my opinion may be useful for the discussion, I'm open to hearing different perspectives and contributing to this restructuring

Thanks for commenting @petruspierre, for sure it's very useful! The only think I don't quite agree with you is that we can have redux and react-query working together. I mean, of course we can, but we don't need to. I think react-query would be better working alone. It's not a replacement for redux because they're totally different, as I said one is a server-side state manager and the other one a client-side. 

Now I think we all agree on having some tool to help us on the backend side. Nest or whatever we may use, for sure we're gonna have patterns and the right way to do something, like introduce a new module. 

Let's avoid reinventing the wheel. We have ready to use solutions like authentication flows that give us reliability and allow us to implement it fast.

So yeah, some conclusions:

1. Not write existent features that open source libraries already do.

2. Create a new branch and start from scratch using the best monorepo tool that we have available. 

3. Firebase would be a short term solution. Should we take another approach? Up votes for nest?

4. We're gonna use expo.

5. We're gonna use Apollo as our GraphQL client.

WDYT guys?

**Comment by belgamo** [comment]
Hey I was mistaken about react-query... Actually doesn't make sense to use react-query with apollo, because Apollo does the same for GraphQL. So technically, we only need Apollo.

**Comment by wendelfreitas** [comment]
I think its a good idea to make animavita more developer-friendly, I was suggesting the simple stack above because its fast to deploy and have something in production to get user feedback to start a version with these technologies that @belgamo said. 

Using firebase we can add other technologies and still using firebase for some functionalities like, we can use firebase functions etc

But it was only a suggestion and I understand your points.

**Comment by belgamo** [comment]
@wendelfreitas could you clarify if it's possible to migrate data from firebase?

**Comment by wendelfreitas** [comment]
you dont have any way directly.  When I needed to do that, I needed to pass from firebase to SQL database using laravel, I created a simple cli-script which read firebase stuff and wrote in our DB @belgamo

**Comment by Lorenzobattistela** [comment]
Greetings, y'all. I am new to this project and to open source, and I am interested in contributing with this restructuring issue.
As a new contributor, I tend to think that the best way to attract more contributors is:
1. Starting the restructure process from scratch, since today the code is hard to understand and contribute.
2. Build an MVP v2 version of it , keeping it simple and well built, maintaining a clean code and test covers.
3. Build detailed documentation on how to contribute with the v2 branch

I will abstain about stacks, but I am taking a good read to understand which tech would be better for this project.
But IMHO, creating a new structure from scratch would help a lot for new contributors, like myself, since it would be a simpler code. But, for this to attract new developers, the documentation needs to be well written and explains some important things.

**Comment by belgamo** [comment]
> you dont have any way directly. When I needed to do that, I needed to pass from firebase to SQL database using laravel, I created a simple cli-script which read firebase stuff and wrote in our DB @belgamo

Humm I don't know if it's worth it... I'd rather start with our own backend but do everything as simple as possible. We already took too long to release it, so I don't think we need to hurry right now. Getting developers should be our first priority to keep this project active, then we think about our users and how we can improve their experience.
I'll start some experiences locally and as make progress I'll let you guys know.

**Comment by Lorenzobattistela** [comment]
lemme know when a new branch is created with strutcure, I will help on it too!

**Comment by joaoGabriel55** [comment]
I think that we can use Firebase for production and use a fake/or simple auth for development environment. For this, as @belgamo said, we can use an abstraction (Strategy pattern) for this, using some env var to auto-select the auth implementation.

About Apollo, it new version provide an out-of-the-box state management, so we can use this feature instead use Redux. See video bellow.

[Dispatch this: Using Apollo Client 3 as a State Management Solution
](https://www.youtube.com/watch?v=xASrlg9rmR4)
Or video article: [Article](https://www.apollographql.com/blog/apollo-client/caching/dispatch-this-using-apollo-client-3-as-a-state-management-solution/)

But, we could use both joined, Redux + Apollo Client.

**Comment by joaoGabriel55** [comment]
About Nest.js usage, we can use Prisma as ORM. The Nest.js has a doc talking about this integration

https://docs.nestjs.com/recipes/prisma
